language: objective-c
xcode_project: easyVideo/easyVideo.xcodeproj
xcode_scheme: easyVideo
podfile: easyVideo/Podfile

script: 
    cd easyVideo; xcodebuild -workspace easyvideo.xcworkspace  -configuration Debug -scheme easyVideo -derivedDataPath ./build
