project 'easyVideo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easyVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for easyVideo
  pod 'MagicalRecord', '~> 2.3.2'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'AliyunOSSiOS'
  pod 'ZipArchive'
  pod 'CocoaLumberjack'

  target 'easyVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'easyVideoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
