//
//  NoticeMacro.h
//  easyVideo
//
//  Created by quanhao huang on 2018/8/17.
//  Copyright © 2018年 easyVideo. All rights reserved.
//

#ifndef NoticeMacro_h
#define NoticeMacro_h

#define CHANGEDISPLAYNAME @"CHANGEDISPLAYNAME"
#define SHOWVIDEO @"SHOWVIDEO"
#define STARTIME @"STARTIME"
#define CANCELCALL @"CANCELCALL"
#define HIDDENLOCAL @"HIDDENLOCAL"
#define SHOWLOCAL @"SHOWLOCAL"
#define REFACTORINGLOCAL @"REFACTORINGLOCAL"
#define REDUCTION @"REDUCTION"
#define AUTOLOGIN @"AUTOLOGIN"
#define JOINCONFID @"JOINCONFID"
#define MEETINGPASSWORD @"MEETINGPASSWORD"
#define JOINMEETING @"JOINMEETING"
#define INVITATIONINFO @"INVITATIONINFO"
#define INVITATIONJOIN @"INVITATIONJOIN"
#define UPLOADIMAGE @"UPLOADIMAGE"
#define MUTENAME @"MUTENAME"
#define ISLOCALMUTE @"ISLOCALMUTE"
#define ANONYMOUSLOGIN @"ANONYMOUSLOGIN"
#define ANONYMOUSLOCATIONLOGIN @"ANONYMOUSLOCATIONLOGIN"
#define WEBJOIN @"WEBJOIN"
#define OPENVIDEO @"OPENVIDEO"
#define ANONYMOUSWEBLOGIN @"ANONYMOUSWEBLOGIN"
#define ANONYMOUSLOCATIONWEBLOGIN @"ANONYMOUSLOCATIONWEBLOGIN"
#define AUTOWEBLOGINJOIN @"AUTOWEBLOGINJOIN"
#define LOGINGOUT @"LOGINGOUT"
#define LOGINGSUCCEED @"LOGINGSUCCEED"
#define UPLOADSU @"UPLOADSU"
#define UPLOADFAIL @"UPLOADFAIL"
#define CLOSEUPLOADWINODW @"CLOSEUPLOADWINODW"
#define REMOVEVIDEO @"REMOVEVIDEO"
#define PORTMPT @"PORTMPT"
#define DOWNLOADURL @"DOWNLOADURL"
#define DONTNEEDUPLODE @"DONTNEEDUPLODE"
#define REGISTERED @"REGISTERED"
#define CHOOSEVIDEO @"CHOOSEVIDEO"

#define CHANGELANGUAGE @"changeLanguage"
#define UPDATETOKEN @"UPDATETOKEN"
#define CLOSELOGINWINDOW @"CLOSELOGINWINDOW"
#define SHOWLOGINWINDOW @"SHOWLOGINWINDOW"
#define CLOSEHOMEWINDOW @"CLOSEHOMEWINDOW"
#define CLOSEUSERWINDOW @"CLOSEUSERWINDOW"
#define CLOSEPDWINDOW @"CLOSEPDWINDOW"
#define CLOSEJOINWINDOW @"CLOSEJOINWINDOW"
#define CLOSEHEADIMAGEWINDOW @"CLOSEHEADIMAGEWINDOW"
#define CLOSEMANMAGEWINDOW @"CLOSEMANMAGEWINDOW"
#define CLOSESIGNLWINDOW @"CLOSESIGNLWINDOW"
#define CLOSECONNECTINGWINDOW @"CLOSECONNECTINGWINDOW"
#define CLOSELOCALWINDOW @"CLOSELOCALWINDOW"
#define CLOSECONTENTWINDOW @"CLOSECONTENTWINDOW"
#define UPLOADMEETINGWEBWINDOW @"UPLOADMEETINGWEBWINDOW"
#define CLOSEMEETINGWEBWINDOW @"CLOSEMEETINGWEBWINDOW"
#define CLOSEPASSWORDWINDOW @"CLOSEPASSWORDWINDOW"
#define CLOSEINVITATIONWINDOW @"CLOSEINVITATIONWINDOW"
#define CLOSEVIDEOHOMEWINDOW @"CLOSEVIDEOHOMEWINDOW"
#define CLOSELOCALCONTENTWINDOW @"CLOSELOCALCONTENTWINDOW"
#define SAVEIMAGE @"SAVEIMAGE"
#define LOCALCONTENTWINDOWDIDCLOSE @"LOCALCONTENTWINDOWDIDCLOSE"
#define CLOSESCREENWINDOW @"CLOSESCREENWINDOW"
#define SENDCONTENT @"SENDCONTENT"

#endif /* NoticeMacro_h */

